# config/packages/vich_uploader.yaml or app/config/config.yml
vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        services:
            uri_prefix: /images/services
            upload_destination: '%kernel.project_dir%/public/images/services'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer